api_key: ${DD_API_KEY}
site: datadoghq.com
hostname: datapulse-analytics

logs_enabled: true
apm_config:
  enabled: true
  env: production

process_config:
  enabled: true

tags:
  - service:datapulse
  - env:production
  - team:analytics

logs_config:
  container_collect_all: true
  processing_rules:
    - type: mask_sequences
      name: mask_api_keys
      replace_placeholder: "[REDACTED]"
      pattern: "(api_key|apikey|token|secret)[=:]\s*['\"]?[\w-]+"

confd:
  postgres.yaml:
    instances:
      - host: datapulse-postgres
        port: 5432
        username: datadog
        dbname: datapulse
        tags:
          - service:datapulse-postgres

  elasticsearch.yaml:
    instances:
      - url: http://datapulse-elasticsearch:9200
        tags:
          - service:datapulse-elasticsearch

  kafka.yaml:
    instances:
      - host: datapulse-kafka
        port: 9092
        tags:
          - service:datapulse-kafka

  redis.yaml:
    instances:
      - host: datapulse-redis
        port: 6379
        tags:
          - service:datapulse-redis
